### ISSUE TITLE
Fix Get Started link

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#112]
Currently when click on Get Started button in footer navigating to `/group/new` replace that to new route `/create-group`
<img width="1432" alt="Screenshot 2024-10-25 at 01 34 25" src="https://github.com/user-attachments/assets/b554a821-ffca-422a-bc18-2b2270db35cf">

**Comment by InderParmar** [comment]
Hi Harsh, the project looks really interesting to me, can you please assign this issue to me, will start working on it asap?
Thank you.

**Comment by harshmangalam** [comment]
Thanks @InderParmar assigned

**Comment by InderParmar** [comment]
@harshmangalam  can you review the PR, and let me know if there are any concerns?

**Comment by InderParmar** [comment]
@harshmangalam can you also please add the "hacktoberfest-accepted" label to this issue.

**Comment by InderParmar** [comment]
@harshmangalam , can you please add the "hacktoberfest-accepted" on this issue too and close this issue as you have merged the PR.
