### ISSUE TITLE
Fix create group card position

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#113]
Move the form card in center of screen

<img width="1432" alt="Screenshot 2024-10-25 at 01 39 17" src="https://github.com/user-attachments/assets/d579555d-11d0-4af6-bada-341411ab2ca5">

**Comment by dexterousdhruv** [comment]
@harshmangalam I'd like to work on it, kindly assign it to me.

**Comment by thejasviES** [comment]
hi @harshmangalam ,I have raised opened PR for the #113 issue
