### ISSUE TITLE
Replace existing text logo with image logo

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#2]
Generate new logo using AI tools that look and feel simple and replace existing text logo with that svg logo
- Make sure it looks like how it is in text format
<img width="257" alt="Screenshot 2024-09-25 at 14 08 23" src="https://github.com/user-attachments/assets/a2913b7b-0ef6-4898-b8b5-33c44d19e7e0">

**Comment by toufiqfarhan0** [comment]
Can you please assign me?

**Comment by kartikey369-ind** [comment]
Hello @harshmangalam. I'd be happy to work on it if you could kindly assign it to me.

**Comment by harshsennnn** [comment]
Hey @harshmangalam can u assign me with this issue

**Comment by harshmangalam** [comment]
@kartikey369-ind are you still interested in this issues ?

**Comment by kartikey369-ind** [comment]
@harshmangalam sorry iam assigned to other work

**Comment by Srijan25** [comment]
can i start working on this can you assign me

**Comment by harshmangalam** [comment]
Okay @Srijan25

**Comment by Srijan25** [comment]
https://www.canva.com/design/DAGTPzucux4/G4vCBW5Lmx8cXrlJ0CgSBQ/edit?utm_content=DAGTPzucux4&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton 
checkout these design should i replace it with this

**Comment by harshmangalam** [comment]
For now it looks good you can add the first one in canva.

**Comment by Srijan25** [comment]
Ok

**Comment by harshmangalam** [comment]
@Srijan25 i tested in my local logo text is looking off it should be bold can you try to acheve somethig like our current text but in image form ?

**Comment by Srijan25** [comment]
oh okay i will do it.

**Comment by Srijan25** [comment]
Hi @harshmangalam I am also looking for job. If you can give my referral its pleased to me.
