### ISSUE TITLE
Create help page

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#21]
Create a new help page inside `/(public)/help`
For reference use this link https://help.meetup.com/hc/en-us

Note
- Do not worry about header and footer design going to utilize the exisiting root layout design.

Add following card
- Organizing Groups and Events
- Using Eventblend
- Technical Issues
- Policies and Community Guidelines

Do not worry about details page for now just create a landing page for help. and for now you can add dummy link to `/help` to card.

**Comment by Pavankumar07s** [comment]
hey @harshmangalam  can i work on this issue.

**Comment by Ashu1823** [comment]
Hi intrested to work in this page. Can you please assign me this one.

**Comment by Pavankumar07s** [comment]
Hey @Ashu1823 , could you please take on a different feature? I've already completed most of my work by creating the header and designing the card.

**Comment by Ashu1823** [comment]
Okay @Pavankumar07s  fine you can continue..

**Comment by harshmangalam** [comment]
@Ashu1823 let me know if you are interested in this issues
https://github.com/harshmangalam/event-blend-frontend/issues/28

**Comment by Pavankumar07s** [comment]
Hey @harshmangalam my exams are going on , so I will be giving updates after few days.

**Comment by Pavankumar07s** [comment]
hey @harshmangalam i have made react page have a look please.
![Screenshot from 2024-10-07 18-22-35](https://github.com/user-attachments/assets/5e02f138-c28d-47dd-bc3c-30689da90cd9)


https://github.com/user-attachments/assets/6d58c300-0c5d-4113-96dc-a863e2e79302

**Comment by harshmangalam** [comment]
Nice, you can create PR i will review and merge.

**Comment by Pavankumar07s** [comment]
@harshmangalam should i have to use the images in topic section??

**Comment by harshmangalam** [comment]
you can utilize meetup image link will design own later.
