### ISSUE TITLE
Do not allow to access auth page for authenticated users

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#26]
After login do not allow user to access `/login` and `/signup` page both auth route are from `(auth)` namespace

**Comment by harshmangalam** [comment]
For reference take help from `(authenticated)` namespace where only authenticated users are allowed to access pages.

**Comment by genial-mani** [comment]
Please assign me I want to work on this.
I have already worked on this before.
You can check here by creating your account on my website it is exactly what I have done.
**link:** https://fullstack-marketing-hub.vercel.app/

> Note: It may take a while to get open, be patient.

**Comment by harshmangalam** [comment]
Thanks @genial-mani  assigned to you

**Comment by harshmangalam** [comment]
@genial-mani any updates ?

**Comment by dead8309** [comment]
Hey can you assign me this ?

**Comment by harshmangalam** [comment]
Okay @dead8309
