### ISSUE TITLE
Add gender section in signup form

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#28]
Add GroupToggle component to accept gender information of user.
- male
- female
- other

For reference https://qwikui.com/docs/headless/toggle-group/

**Note:**
- Add gender field above `age` field
- Also send `gender` field to backend during signup.
- Add zod validations

<img width="921" alt="Screenshot 2024-10-03 at 1 12 13 AM" src="https://github.com/user-attachments/assets/0f3325f3-9b0f-4340-8546-80def7de3ab1">

**Comment by chaitanya-bhargava** [comment]
I would like to work on this!

**Comment by harshmangalam** [comment]
Thanks @chaitanya-bhargava assigned

**Comment by chaitanya-bhargava** [comment]
Hey @harshmangalam, I am facing much difficulty in setting up the frontend and backend locally so I would like to opt out from this issue. Sorry for the inconvenience!

**Comment by TheAdich** [comment]
Hey @harshmangalam  for the gender part i have set up that feature in backend and raised a PR so,  I can integrate this on the client side too asap. Would love to solve this issue . Pls assign this to me

**Comment by harshmangalam** [comment]
Done @TheAdich

**Comment by harshmangalam** [comment]
@TheAdich any updates on this ?

**Comment by TheAdich** [comment]
Will do it today

**Comment by harshmangalam** [comment]
Thanks @TheAdich
