### ISSUE TITLE
Create password reset form

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#4]
- Create new page inside path `/(auth)/reset-password/index.tsx`
- Add password reset form using Qwik Ui, tailwindcss design suggested in screenshot.
- For now do not worry about api integration will look for that once api for reset password will be ready.

<img width="437" alt="Screenshot 2024-09-27 at 16 04 11" src="https://github.com/user-attachments/assets/727a5c9c-be09-4169-9891-b64fb8596ed8">

**Comment by Alienimnida** [comment]
Hello there can I take this up?

**Comment by kartikey369-ind** [comment]
Hello @harshmangalam, I noticed the issue . I'd be happy to work on it if you could kindly assign it to me.

**Comment by harshsennnn** [comment]
Hey @harshmangalam can u assign me with this issue

**Comment by Alienimnida** [comment]
Hello @harshmangalam while setting up it keeps giving me this error:
Cannot read properties of undefined (reading 'data')
I am running the backend as well but I guess it is struggling to connect with the database.

**Comment by harshmangalam** [comment]
Have you setup the env variables from both frontend and backend site ?

**Comment by Alienimnida** [comment]
Hello yes I have

**Comment by harshmangalam** [comment]
Just pushed a fix can you take the latest pull from main and try again

**Comment by Alienimnida** [comment]
Oh ok

**Comment by Alienimnida** [comment]
The issue is still persisting. Did you push the fix to backend or frontend?

**Comment by harshmangalam** [comment]
Frontend

**Comment by Alienimnida** [comment]
Still showing the same error to me

**Comment by Alienimnida** [comment]
Should I share the error page here?

**Comment by harshmangalam** [comment]
Yes sure

**Comment by Alienimnida** [comment]
![error](https://github.com/user-attachments/assets/5a1bce4f-3ecf-40c1-b09b-ed1c9855022b)
See this is the issue

**Comment by harshmangalam** [comment]
This issues was due to auth token and not handling the error case that  fix i pushed to main. Let me know if we can connect to debug more into issues if you still face after latest pull  from main

**Comment by Alienimnida** [comment]
Well I have pulled your latest changes but it keeps persisting will it be possible to connect in Discord?

**Comment by Alienimnida** [comment]
I have messaged you in twitter

**Comment by Alienimnida** [comment]
Actually I have never used Postgres so I'll have to set it up will let you know as soon as I'm done with it

**Comment by harshmangalam** [comment]
Thanks let me know if you need  any help to setup postgres you can message in Eventblend discord channel.

**Comment by Alienimnida** [comment]
Yes thank you very much
