### ISSUE TITLE
Fix Footer link text opacity

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#43]
Footer link text opacity is too low increase its opacity to look good.
<img width="853" alt="Screenshot 2024-10-09 at 1 33 36 PM" src="https://github.com/user-attachments/assets/e46a95c9-a3f1-439c-9ba5-bcc9e0a10ef8">

**Comment by harshmangalam** [comment]
@Srijan25 assigned

**Comment by Srijan25** [comment]
![image](https://github.com/user-attachments/assets/61ba6c94-bab2-4d66-be44-7f61fde90b41)
 getting this error after loading

**Comment by harshmangalam** [comment]
have you configured the local backend ?
