### ISSUE TITLE
Add bold text in location label

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#45]
In Explore popular cities section card add text bold for city name in home page.
<img width="1305" alt="Screenshot 2024-10-09 at 1 38 44 PM" src="https://github.com/user-attachments/assets/48662689-3e77-402a-a4b5-3db6c12c01f9">

**Comment by tharikashree** [comment]
Hey can i work on this ?

**Comment by harshmangalam** [comment]
@tharikashree thanks assigned
