### ISSUE TITLE
Extend menu links inside account dropdown

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#5]
Extend account dropdown menu by adding these links
- Create group  :-  link to `/create-group` page
- Create event :- link to `/create-event` page

Note:
- Please login first 
- Add these create link with new separator 
<img width="1422" alt="Screenshot 2024-09-27 at 16 16 44" src="https://github.com/user-attachments/assets/d8097739-5166-4a74-a516-f143c0b8a74e">

**Comment by SeanAverS** [comment]
Hi, 

Interested on working on this. Could I please be assigned? Thanks.

**Comment by Pavankumar07s** [comment]
Hey @harshmangalam i want to work on this issue 😊 .

**Comment by ajay0180** [comment]
i want to work on this issue.

**Comment by harshsennnn** [comment]
Hey i want to work on this issue can u assign me this

**Comment by harshsennnn** [comment]
Great going mate

**Comment by Pavankumar07s** [comment]
Hey @harshmangalam thankyou for accepting my pr ,please close the issue with hacktoberfest-accept badge😊
