### ISSUE TITLE
Add Support or refrence for get GEOAPIFY_API_KEY 

### ISSUE THREAD

**Issue by imkuldeepahlawat** [harshmangalam/event-blend-frontend#58]
Add Support or refrence for get GEOAPIFY_API_KEY, related links 
update readme md file

**Comment by harshmangalam** [comment]
Okay i will create a new ticket for this.

**Comment by harshmangalam** [comment]
@imkuldeepahlawat are you working on this can i assign to you ?

**Comment by imkuldeepahlawat** [comment]
sure
