### ISSUE TITLE
Add link to group details in event card

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#62]
- Visit home page
- Go to Explore popular events section
- Now complete card is work as a link card and link to Event details
- There add group link to `/:group-slug` in Hosted by 
- Whole card will be navigate to event details but Hosted by group name will navigate to group details.
<img width="478" alt="Screenshot 2024-10-12 at 11 06 13 AM" src="https://github.com/user-attachments/assets/4e8ba5d2-19c5-41cc-ade9-8c95219fafbb">

**Comment by InderParmar** [comment]
Hi, I am eager to work on this issue, can you please assign this issue to me?

**Comment by harshmangalam** [comment]
Thanks assigned
