### ISSUE TITLE
Fix Group details page events count update 

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#77]
When clicking on button Join the group its also updating events count. It should only update members

https://github.com/user-attachments/assets/0095d77a-4db3-43ca-9d2a-2a0a45a54ce7

**Comment by mokshith-moksh** [comment]
can you assign this issue to me

**Comment by harshmangalam** [comment]
@mokshith-moksh assigned

**Comment by mokshith-moksh** [comment]
how to create a category

**Comment by mokshith-moksh** [comment]
issue resolved
