### ISSUE TITLE
Add create new event button

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#78]
When open any group add a new button `Create event` after `Join this group` and that will only render for group admin not for other users.
<img width="1350" alt="Screenshot 2024-10-18 at 12 49 03" src="https://github.com/user-attachments/assets/89291c6e-dd2b-4c25-af1a-ac75c36c7470">

**Comment by InderParmar** [comment]
Hi, I am eager to work on this issue, can you please assign this issue to me?

**Comment by harshmangalam** [comment]
Thanks assigned
