### ISSUE TITLE
Replace existing create event description textarea with rich text editor #80

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#81]
Currently When we are creating a new event the description is a textarea replace this with lightweight text editor that provide basic text transformation

listing
bold
ilatic
etc...

**Comment by HarshitPachori** [comment]
Hii @harshmangalam ,
Assign me this issue , I would like to work on it.

**Comment by harshmangalam** [comment]
Sure @HarshitPachori assigned
