### ISSUE TITLE
Fix image border radius

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/event-blend-frontend#91]
In home page fix image border radius . The image border radius must be same as card border radius
<img width="1102" alt="Screenshot 2024-10-19 at 01 23 34" src="https://github.com/user-attachments/assets/4a0b3909-949e-4612-a30e-a72650a56463">

**Comment by harshmangalam** [comment]
Also fix the same for event card

**Comment by askarthikey** [comment]
Heyy @harshmangalam I would like to work on this issue. Can you please assign me this

**Comment by harshmangalam** [comment]
@askarthikey  assigned

**Comment by askarthikey** [comment]
Thank you I will be working on it

**Comment by tharikashree** [comment]
Hey is this still open?
If so,can i work on this?

**Comment by harshmangalam** [comment]
@tharikashree assigned to you
